name = "aham-cloudflare"
main = "src/worker.js"
compatibility_date = "2026-03-05"
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "aham_calendar"
database_id = "81541a60-053c-4ca7-b1b4-b45c98984b4b"
